(()=>{'use strict';
const KEY='leadforge.v3'; const LEGACY='lf-leads';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const clean=v=>String(v??'').trim(); const domain=u=>clean(u).replace(/^https?:\/\//i,'').replace(/^www\./i,'').split(/[/?#]/)[0].toLowerCase();
const initials=n=>clean(n).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?';
function blank(){return {id:id(),name:'',category:'',website:'',email:'',phone:'',location:'',status:'New',notes:'',source:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function normalize(x){return {...blank(),...x,id:x.id||id(),name:clean(x.name||x.company),website:clean(x.website||x.url),location:clean(x.location||[x.city,x.state].filter(Boolean).join(', ')),status:['New','Review','Qualified','Archived'].includes(x.status)?x.status:'New'}}
function migrate(){try{const own=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(own))return own.map(normalize);const old=JSON.parse(localStorage.getItem(LEGACY)||'null');if(Array.isArray(old)){const real=old.filter(x=>!String(x.email||'').endsWith('.example')&&!String(x.website||'').includes('.example'));localStorage.setItem(KEY,JSON.stringify(real.map(normalize)));return real.map(normalize)}}catch(_){}return []}
let leads=migrate(), filter='All', query='', draft=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(leads));return true}catch(_){toast('This browser could not save the change. Free some storage and try again.');return false}}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)}
function score(l){let s=15;if(l.name)s+=20;if(l.website)s+=18;if(l.email)s+=18;if(l.phone)s+=12;if(l.location)s+=8;if(l.category)s+=5;if(l.source)s+=4;return Math.min(100,s)}
const contactable=l=>!!(l.email||l.phone); const duplicateFor=l=>leads.find(x=>x.id!==l.id&&((domain(l.website)&&domain(l.website)===domain(x.website))||(l.email&&l.email.toLowerCase()===String(x.email).toLowerCase())||(l.phone&&l.phone.replace(/\D/g,'').length>6&&l.phone.replace(/\D/g,'')===String(x.phone).replace(/\D/g,''))));
function route(){const r=['overview','leads','capture'].includes(location.hash.slice(1))?location.hash.slice(1):'overview';$$('.view').forEach(v=>v.hidden=v.id!==r);$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===r));$('#pageTitle').textContent={overview:'Overview',leads:'Leads',capture:'Capture'}[r];render(r);scrollTo(0,0)}
function syncChrome(){$('#navCount').textContent=leads.length;$('#storageNote').textContent=`${leads.length} record${leads.length===1?'':'s'} · nothing uploaded`}
function render(r){syncChrome();if(r==='overview')renderOverview();if(r==='leads')renderLeads();if(r==='capture')renderCapture()}
function empty(title,copy,cta='Capture your first lead'){return `<div class="empty"><div class="empty-icon">◎</div><h3>${title}</h3><p>${copy}</p><a class="button primary" href="#capture">${cta}</a></div>`}
function renderOverview(){const missing=leads.filter(l=>!l.email&&!l.phone).length, review=leads.filter(l=>l.status==='Review'||score(l)<60).length, qualified=leads.filter(l=>l.status==='Qualified').length, avg=leads.length?Math.round(leads.reduce((a,l)=>a+score(l),0)/leads.length):0;$('#overview').innerHTML=`<div class="hero"><article class="hero-copy"><span class="kicker">EXPLAINABLE PROSPECTING</span><h2>Build a list you can trust later.</h2><p>Capture public details with their source, spot duplicates before they spread, and move only complete records forward.</p></article><aside class="next-panel"><h3>Needs attention</h3><div class="next-list"><a class="next-item quiet-link" href="#leads" data-filter-jump="Review"><span>◌</span><div><strong>Review queue</strong><small>Low confidence or marked for review</small></div><span class="count">${review}</span></a><a class="next-item quiet-link" href="#leads" data-filter-jump="Missing contact"><span>⌁</span><div><strong>Missing a contact</strong><small>No email or phone yet</small></div><span class="count">${missing}</span></a></div></aside></div><div class="metrics"><div class="metric"><span>TOTAL LEADS</span><strong>${leads.length}</strong><small>on this device</small></div><div class="metric"><span>CONTACTABLE</span><strong>${leads.filter(contactable).length}</strong><small>email or phone</small></div><div class="metric"><span>QUALIFIED</span><strong>${qualified}</strong><small>ready to use</small></div><div class="metric"><span>AVG. COMPLETENESS</span><strong>${avg}%</strong><small>field coverage</small></div></div><div class="panel"><div class="panel-head"><h3>Recently updated</h3>${leads.length?'<a href="#leads" class="quiet-link">See all leads</a>':''}</div>${leads.length?list(leads.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,5),false):empty('Start with evidence, not a spreadsheet','Paste a public listing or enter one record manually. LeadForge keeps the source beside the details.')}</div>`;$$('[data-filter-jump]').forEach(a=>a.onclick=()=>{filter=a.dataset.filterJump})}
function visible(){return leads.filter(l=>{const hay=[l.name,l.category,l.website,l.email,l.phone,l.location,l.notes].join(' ').toLowerCase();const f=filter==='All'||(filter==='Missing contact'&&!contactable(l))||l.status===filter;return f&&hay.includes(query.toLowerCase())}).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
function list(items,head=true){if(!items.length)return empty('No leads match','Try a different search or filter.','Capture a lead');return `<div class="lead-list">${head?'<div class="lead-row head"><div>BUSINESS</div><div>CONTACT</div><div>LOCATION</div><div>COMPLETE</div><div>STATUS</div></div>':''}${items.map(l=>`<div class="lead-row" data-open="${esc(l.id)}" tabindex="0" role="button" aria-label="Open ${esc(l.name||'unnamed lead')}"><div class="company"><span class="avatar">${esc(initials(l.name))}</span><span><strong>${esc(l.name||'Unnamed lead')}</strong><small>${esc(l.category||domain(l.website)||'No category')}</small></span></div><div class="contact"><span>${esc(l.email||'No email')}</span><small>${esc(l.phone||domain(l.website)||'No phone')}</small></div><div class="contact"><span>${esc(l.location||'No location')}</span><small>${esc(domain(l.website)||'No website')}</small></div><div class="confidence">${score(l)}% <small>complete</small></div><div><span class="badge ${l.status.toLowerCase()}">${esc(l.status)}</span></div></div>`).join('')}</div>`}
function bindRows(root){$$('[data-open]',root).forEach(x=>{x.onclick=()=>openLead(x.dataset.open);x.onkeydown=e=>{if(e.key==='Enter')openLead(x.dataset.open)}})}
function renderLeads(){const v=visible();$('#leads').innerHTML=`<div class="tools"><input id="search" class="input" type="search" placeholder="Search company, email, city, notes…" value="${esc(query)}"><select id="filter" class="input" aria-label="Filter leads">${['All','New','Review','Qualified','Missing contact','Archived'].map(x=>`<option${x===filter?' selected':''}>${x}</option>`).join('')}</select><a href="#capture" class="button primary">Capture lead</a></div><div class="panel"><div class="panel-head"><h3>${v.length} lead${v.length===1?'':'s'}</h3><span class="hint">Select a row to review, edit, or archive it.</span></div>${list(v)}</div>`;$('#search').oninput=e=>{query=e.target.value;renderLeads()};$('#filter').onchange=e=>{filter=e.target.value;renderLeads()};bindRows($('#leads'))}
function parseText(text){const lines=text.split(/\n+/).map(clean).filter(Boolean);const email=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'';const phone=(text.match(/(?:\+?\d[\d\s().-]{7,}\d)/)||[])[0]||'';const url=(text.match(/(?:https?:\/\/|www\.)[^\s,]+/i)||[])[0]||'';const ignore=l=>l===email||l===phone||l.includes(url)||/^(address|phone|email|website|hours|open|closed)\b/i.test(l);const name=lines.find(l=>!ignore(l)&&l.length<90&&!/^\d/.test(l))||'';const loc=lines.find(l=>l!==name&&!ignore(l)&&(/,/.test(l)||/\b(?:street|st\.?|road|rd\.?|avenue|ave\.?|lane|ln\.?|drive|dr\.?|boulevard|blvd\.?|suite)\b/i.test(l)))||'';return normalize({...blank(),name,email,phone,website:url,location:loc,source:text.slice(0,1500),status:'Review'})}
function renderCapture(){draft=null;$('#capture').innerHTML=`<div class="capture-grid"><div class="panel capture-box"><span class="kicker">SMART PASTE</span><h2>Turn a public listing into a reviewable record.</h2><p>Paste a directory listing, website contact block, or map result. Extraction runs only in this browser.</p><div class="field"><label for="paste">PUBLIC DETAILS</label><textarea id="paste" class="paste" placeholder="Paste the business name, website, email, phone, address…"></textarea><span class="hint">LeadForge never visits the source or sends this text anywhere.</span></div><button id="extract" class="button primary">Extract details</button><div id="review" class="review-card" hidden></div></div><div class="panel capture-box"><span class="kicker">MANUAL ENTRY</span><h2>Add a lead with context.</h2><p>Keep the source or reason beside the record, so future-you can verify it.</p><form id="manual" class="form-grid">${fields()}<div class="wide"><button class="button primary" type="submit">Save lead</button></div></form></div></div>`;$('#extract').onclick=extract;$('#manual').onsubmit=e=>{e.preventDefault();const l=fromForm(e.currentTarget);commit(l)}}
function fields(l={}){return `<div class="field wide"><label>BUSINESS NAME *</label><input name="name" required value="${esc(l.name)}" placeholder="Northline Studio"></div><div class="field"><label>WEBSITE</label><input name="website" value="${esc(l.website)}" placeholder="https://example.com"></div><div class="field"><label>CATEGORY</label><input name="category" value="${esc(l.category)}" placeholder="Architecture studio"></div><div class="field"><label>EMAIL</label><input name="email" type="email" value="${esc(l.email)}" placeholder="hello@example.com"></div><div class="field"><label>PHONE</label><input name="phone" value="${esc(l.phone)}" placeholder="+1 555 0123"></div><div class="field wide"><label>LOCATION</label><input name="location" value="${esc(l.location)}" placeholder="City, region"></div><div class="field wide"><label>SOURCE / NOTES</label><textarea name="source" placeholder="Where did this come from?">${esc(l.source)}</textarea></div>`}
function fromForm(f,base=blank()){const d=new FormData(f), l={...base};['name','website','category','email','phone','location','source','notes','status'].forEach(k=>{if(d.has(k))l[k]=clean(d.get(k))});l.updatedAt=new Date().toISOString();return normalize(l)}
function extract(){const text=clean($('#paste').value);if(!text){toast('Paste some public business details first.');return}draft=parseText(text);const dup=duplicateFor(draft);$('#review').hidden=false;$('#review').innerHTML=`<h4>Review the extraction</h4><div class="review-grid"><div><small>BUSINESS</small>${esc(draft.name||'Not found')}</div><div><small>WEBSITE</small>${esc(draft.website||'Not found')}</div><div><small>EMAIL</small>${esc(draft.email||'Not found')}</div><div><small>PHONE</small>${esc(draft.phone||'Not found')}</div><div><small>LOCATION</small>${esc(draft.location||'Not found')}</div><div><small>COMPLETENESS</small>${score(draft)}%</div></div>${dup?`<div class="duplicate">Possible duplicate: <b>${esc(dup.name)}</b>. Open it to merge these details instead.</div>`:''}<div class="modal-actions">${dup?`<button class="button ghost" id="merge">Review duplicate</button>`:''}<button class="button primary" id="saveExtracted" ${draft.name?'':'disabled'}>Save for review</button></div>`;$('#saveExtracted').onclick=()=>commit(draft);if(dup)$('#merge').onclick=()=>openLead(dup.id,draft)}
function commit(l){if(!clean(l.name)){toast('Add a business name before saving.');return}const dup=duplicateFor(l);if(dup&&!confirm(`A matching lead already exists: ${dup.name}. Save a separate record anyway?`))return;leads.unshift(normalize(l));if(save()){toast('Lead saved to this device.');location.hash='leads'}}
function openLead(leadId,incoming=null){const l=leads.find(x=>x.id===leadId);if(!l)return;const merged=incoming?{...l,...Object.fromEntries(Object.entries(incoming).filter(([k,v])=>v&&!l[k]))}:l;const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="leadTitle"><button class="close" aria-label="Close">×</button><h2 id="leadTitle">${incoming?'Merge into ':'Review '}${esc(l.name)}</h2><p>${incoming?'Missing fields from the captured details have been filled below. Review before saving.':'Keep the record useful, sourced, and ready for its next step.'}</p><form id="leadForm" class="form-grid">${fields(merged)}<div class="field"><label>STATUS</label><select name="status">${['New','Review','Qualified','Archived'].map(x=>`<option${x===merged.status?' selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>PRIVATE NOTES</label><textarea name="notes" placeholder="Why is this lead relevant?">${esc(merged.notes)}</textarea></div></form><div class="evidence">Completeness: ${score(merged)}% · ${merged.source?'Source context saved':'No source context yet'}</div><div class="modal-actions"><button id="deleteLead" class="button danger">Delete</button><button id="cancelLead" class="button ghost">Cancel</button><button id="saveLead" class="button primary">Save changes</button></div></div></div>`;const close=()=>root.innerHTML='';$('.close',root).onclick=close;$('#cancelLead').onclick=close;$('.modal-backdrop',root).onclick=e=>{if(e.target===e.currentTarget)close()};$('#saveLead').onclick=()=>{const changed=fromForm($('#leadForm'),merged);leads=leads.map(x=>x.id===l.id?changed:x);if(save()){toast('Lead updated.');close();render(location.hash.slice(1)||'overview')}};$('#deleteLead').onclick=()=>{if(confirm(`Delete ${l.name}? This cannot be undone.`)){leads=leads.filter(x=>x.id!==l.id);save();close();render(location.hash.slice(1)||'overview');toast('Lead deleted.')}}}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(clean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(clean))rows.push(row);if(rows.length<2)return[];const h=rows[0].map(x=>clean(x).toLowerCase());return rows.slice(1).map(r=>{const o={};h.forEach((k,i)=>o[k]=clean(r[i]));return normalize({name:o.name||o.company||o.business,website:o.website||o.url,email:o.email,phone:o.phone,location:o.location||o.city,category:o.category,status:o.status,notes:o.notes,source:o.source||'CSV import'})}).filter(x=>x.name)}
function csvCell(v){v=String(v??'');return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}function exportCSV(){if(!leads.length){toast('There are no leads to export yet.');return}const keys=['name','website','category','email','phone','location','status','notes','source'];const text=[keys.join(','),...leads.map(l=>keys.map(k=>csvCell(l[k])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=`leadforge-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('CSV export ready.')}
function dataModal(){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="close">×</button><h2>Your local data</h2><p>LeadForge stores records only in this browser's local storage. Export a backup before clearing it.</p><div class="evidence">${leads.length} record${leads.length===1?'':'s'} on this device. No account, server, analytics, or background enrichment.</div><div class="modal-actions"><button id="clearAll" class="button danger">Clear all records</button><button id="backup" class="button primary">Export backup</button></div></div></div>`;$('.close',root).onclick=()=>root.innerHTML='';$('#backup').onclick=exportCSV;$('#clearAll').onclick=()=>{if(confirm('Clear every LeadForge record on this device? Export first if you need a backup.')){leads=[];save();root.innerHTML='';route();toast('Local LeadForge data cleared.')}}}
$('#importButton').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const rows=parseCSV(await f.text());if(!rows.length){toast('No usable rows found. Include a name or company column.');return}const unique=rows.filter(r=>!duplicateFor(r));leads=[...unique,...leads];save();toast(`Imported ${unique.length} lead${unique.length===1?'':'s'}${rows.length!==unique.length?' · duplicates skipped':''}.`);location.hash='leads'}catch(_){toast('That CSV could not be read. Check the file and try again.')}finally{e.target.value=''}};$('#exportButton').onclick=exportCSV;$('#dataButton').onclick=dataModal;$('#mobileCapture').onclick=()=>location.hash='capture';window.addEventListener('hashchange',route);route();
})();
